name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - folium
  - wordcloud
  - matplotlib
  - scipy=1.8.1
  - gensim=4.1.2
  - nltk
  - pip>20.3
  - rasterio
  - scikit-learn
  - pillow
  - pip:
    - jupyter
    - tensorflow
    - numpy==1.23.0
postBuild: |
  python -c "import nltk; nltk.download('punkt')"
